void f(int x) throws int {
  try {
    print(x, "\n");
    if(x >=3) {
      throw -1;
    } else {
      g(x+1);
    }
  } catch(bool b) {
    print("Wrong\n");  // never reaches this
  }
  print("Wrong\n");  // never reaches this
}

void g(int x) throws int {
  try {
    f(x);
  } catch(string s) {
    print("Wrong\n");  // never reaches this
  }
  print("Wrong\n");  // never reaches this
}

void main() {
  try {
    f(1);
  } catch(int x) {
    print("OK\n");
  }
  print("Done\n");
}
